create table sensor(
    id int generated by default as identity primary key,
    name varchar unique not null
);

create table measurement(
    id int generated by default as identity primary key,
    sensor_name varchar references sensor(name),
    value double precision not null,
    raining boolean not null,
    created_at timestamp not null
);